version: '3.8'

services:
  mongodb:
    container_name: test_mongodb
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  api:
    container_name: test_app
    build: .
    volumes:
      - ./:/usr/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: always
volumes:
  mongodb_data_container:
